# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Fri Jul 05 02:53:06 2013
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(615, 518)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushOutput = QtGui.QPushButton(self.centralwidget)
        self.pushOutput.setEnabled(False)
        self.pushOutput.setObjectName(_fromUtf8("pushOutput"))
        self.gridLayout.addWidget(self.pushOutput, 3, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.comboBox = QtGui.QComboBox(self.tab)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/dungeon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon, _fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/battle.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon1, _fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/item.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon2, _fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/parts.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon3, _fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/other.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon4, _fromUtf8(""))
        self.comboBox.addItem(icon2, _fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/gatya.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon5, _fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/mission_1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon6, _fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/mission_2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon7, _fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/labo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon8, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox, 0, 2, 1, 1)
        self.pushCount = QtGui.QPushButton(self.tab)
        self.pushCount.setEnabled(True)
        self.pushCount.setObjectName(_fromUtf8("pushCount"))
        self.gridLayout_2.addWidget(self.pushCount, 0, 3, 1, 1)
        self.treeResult = QtGui.QTreeWidget(self.tab)
        self.treeResult.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.treeResult.setIndentation(0)
        self.treeResult.setObjectName(_fromUtf8("treeResult"))
        self.gridLayout_2.addWidget(self.treeResult, 1, 0, 1, 4)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.checkUser = QtGui.QCheckBox(self.tab_2)
        self.checkUser.setObjectName(_fromUtf8("checkUser"))
        self.gridLayout_4.addWidget(self.checkUser, 0, 1, 1, 1)
        self.checkInfo = QtGui.QCheckBox(self.tab_2)
        self.checkInfo.setObjectName(_fromUtf8("checkInfo"))
        self.gridLayout_4.addWidget(self.checkInfo, 0, 0, 1, 1)
        self.labelFile = QtGui.QLabel(self.tab_2)
        self.labelFile.setObjectName(_fromUtf8("labelFile"))
        self.gridLayout_4.addWidget(self.labelFile, 1, 0, 1, 1)
        self.labelText = QtGui.QLabel(self.tab_2)
        self.labelText.setObjectName(_fromUtf8("labelText"))
        self.gridLayout_4.addWidget(self.labelText, 1, 1, 1, 1)
        self.labelSearch = QtGui.QLabel(self.tab_2)
        self.labelSearch.setObjectName(_fromUtf8("labelSearch"))
        self.gridLayout_4.addWidget(self.labelSearch, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 1, 0, 1, 2)
        self.treeSearch = QtGui.QTreeWidget(self.tab_2)
        self.treeSearch.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.treeSearch.setIndentation(0)
        self.treeSearch.setObjectName(_fromUtf8("treeSearch"))
        self.gridLayout_3.addWidget(self.treeSearch, 4, 0, 1, 2)
        self.lineSearch = QtGui.QLineEdit(self.tab_2)
        self.lineSearch.setObjectName(_fromUtf8("lineSearch"))
        self.gridLayout_3.addWidget(self.lineSearch, 0, 0, 1, 1)
        self.pushSearch = QtGui.QPushButton(self.tab_2)
        self.pushSearch.setEnabled(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushSearch.setIcon(icon9)
        self.pushSearch.setObjectName(_fromUtf8("pushSearch"))
        self.gridLayout_3.addWidget(self.pushSearch, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 2, 0, 1, 2)
        self.frameOption = QtGui.QFrame(self.centralwidget)
        self.frameOption.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameOption.setFrameShadow(QtGui.QFrame.Raised)
        self.frameOption.setObjectName(_fromUtf8("frameOption"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frameOption)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.radioButton_3 = QtGui.QRadioButton(self.frameOption)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.radioGroup = QtGui.QButtonGroup(MainWindow)
        self.radioGroup.setObjectName(_fromUtf8("radioGroup"))
        self.radioGroup.addButton(self.radioButton_3)
        self.gridLayout_5.addWidget(self.radioButton_3, 0, 3, 1, 1)
        self.radioButton = QtGui.QRadioButton(self.frameOption)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.radioGroup.addButton(self.radioButton)
        self.gridLayout_5.addWidget(self.radioButton, 0, 1, 1, 1)
        self.radioButton_2 = QtGui.QRadioButton(self.frameOption)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.radioGroup.addButton(self.radioButton_2)
        self.gridLayout_5.addWidget(self.radioButton_2, 0, 2, 1, 1)
        self.radioButton_4 = QtGui.QRadioButton(self.frameOption)
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.radioGroup.addButton(self.radioButton_4)
        self.gridLayout_5.addWidget(self.radioButton_4, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.comboStart = QtGui.QComboBox(self.frameOption)
        self.comboStart.setObjectName(_fromUtf8("comboStart"))
        self.horizontalLayout_2.addWidget(self.comboStart)
        self.labelOption = QtGui.QLabel(self.frameOption)
        self.labelOption.setObjectName(_fromUtf8("labelOption"))
        self.horizontalLayout_2.addWidget(self.labelOption)
        self.comboEnd = QtGui.QComboBox(self.frameOption)
        self.comboEnd.setObjectName(_fromUtf8("comboEnd"))
        self.horizontalLayout_2.addWidget(self.comboEnd)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 1, 0, 1, 4)
        self.gridLayout.addWidget(self.frameOption, 1, 0, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushCapture = QtGui.QPushButton(self.centralwidget)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/photo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushCapture.setIcon(icon10)
        self.pushCapture.setObjectName(_fromUtf8("pushCapture"))
        self.horizontalLayout.addWidget(self.pushCapture)
        self.pushOption = QtGui.QPushButton(self.centralwidget)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/tools.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushOption.setIcon(icon11)
        self.pushOption.setObjectName(_fromUtf8("pushOption"))
        self.horizontalLayout.addWidget(self.pushOption)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 615, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.FileMenu = QtGui.QMenu(self.menubar)
        self.FileMenu.setObjectName(_fromUtf8("FileMenu"))
        self.HelpMenu = QtGui.QMenu(self.menubar)
        self.HelpMenu.setObjectName(_fromUtf8("HelpMenu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/quit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon12)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionHelp = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon13)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionAbout = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/page.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon14)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionCopy = QtGui.QAction(MainWindow)
        self.actionCopy.setIcon(icon14)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.FileMenu.addAction(self.actionCopy)
        self.FileMenu.addAction(self.actionExit)
        self.HelpMenu.addAction(self.actionAbout)
        self.HelpMenu.addAction(self.actionHelp)
        self.menubar.addAction(self.FileMenu.menuAction())
        self.menubar.addAction(self.HelpMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.pushSearch, QtCore.SIGNAL(_fromUtf8("clicked()")), self.treeSearch.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "C21 ログ解析", None))
        self.pushOutput.setText(_translate("MainWindow", "書き出し", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "遺跡", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "撃破", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "取得/アイテム", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "取得/パーツ", None))
        self.comboBox.setItemText(4, _translate("MainWindow", "取得/ギルドポイント", None))
        self.comboBox.setItemText(5, _translate("MainWindow", "報酬/アイテム・パーツ", None))
        self.comboBox.setItemText(6, _translate("MainWindow", "ガチャ", None))
        self.comboBox.setItemText(7, _translate("MainWindow", "基地", None))
        self.comboBox.setItemText(8, _translate("MainWindow", "突発", None))
        self.comboBox.setItemText(9, _translate("MainWindow", "ラボ", None))
        self.pushCount.setText(_translate("MainWindow", "カウント", None))
        self.treeResult.setSortingEnabled(False)
        self.treeResult.headerItem().setText(0, _translate("MainWindow", "名称", None))
        self.treeResult.headerItem().setText(1, _translate("MainWindow", "周回数/撃破数/獲得数", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "ログ解析", None))
        self.checkUser.setText(_translate("MainWindow", "ユーザー発言をスキップ（NPC含む）", None))
        self.checkInfo.setText(_translate("MainWindow", "［INFO］ログをスキップ", None))
        self.labelFile.setText(_translate("MainWindow", "対象ファイル数　：　", None))
        self.labelText.setText(_translate("MainWindow", "検索文字列　：　", None))
        self.labelSearch.setText(_translate("MainWindow", "合致数　：　", None))
        self.treeSearch.setSortingEnabled(True)
        self.treeSearch.headerItem().setText(0, _translate("MainWindow", "日時", None))
        self.treeSearch.headerItem().setText(1, _translate("MainWindow", "ログ", None))
        self.pushSearch.setText(_translate("MainWindow", "検索", None))
        self.pushSearch.setShortcut(_translate("MainWindow", "Return", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "ログ検索", None))
        self.radioButton_3.setText(_translate("MainWindow", "指定した期間", None))
        self.radioButton.setText(_translate("MainWindow", "今日", None))
        self.radioButton_2.setText(_translate("MainWindow", "指定した日", None))
        self.radioButton_4.setText(_translate("MainWindow", "すべて", None))
        self.labelOption.setText(_translate("MainWindow", "から", None))
        self.pushCapture.setText(_translate("MainWindow", "画像書き出し", None))
        self.pushOption.setText(_translate("MainWindow", "設定", None))
        self.FileMenu.setTitle(_translate("MainWindow", "ファイル(&F)", None))
        self.HelpMenu.setTitle(_translate("MainWindow", "ヘルプ(&H)", None))
        self.actionExit.setText(_translate("MainWindow", "終了", None))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionHelp.setText(_translate("MainWindow", "ヘルプ", None))
        self.actionHelp.setShortcut(_translate("MainWindow", "Ctrl+H", None))
        self.actionAbout.setText(_translate("MainWindow", "このソフトについて", None))
        self.actionCopy.setText(_translate("MainWindow", "コピー", None))
        self.actionCopy.setToolTip(_translate("MainWindow", "コピー", None))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C", None))

import res_rc
